version: '3.8'

services:
  app:
    build: .
    container_name: uksimracing-app
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP (internal for Let's Encrypt challenges only)
      - "443:443"   # HTTPS (external)
    environment:
      - NODE_ENV=production
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - DOMAIN=uksimracing.co.uk
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./uploads:/app/public/uploads
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot:/var/www/certbot
    networks:
      - uksimracing
      

  discord-bot:
    build: ./discord-bot
    container_name: uksimracing-discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - WEBSITE_URL=http://app:80
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - TRIGGER_MENTION=UKSimRacingWebsite
    env_file:
      - .env
    networks:
      - uksimracing
    depends_on:
      - app

networks:
  uksimracing:
    driver: bridge