version: '3.8'

services:
  web:
    build: .
    ports:
      - "2000:2000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DISCORD_WEBHOOK_SECRET=${DISCORD_WEBHOOK_SECRET}
    restart: unless-stopped
    networks:
      - uksimracing

  discord-bot:
    build: ./discord-bot
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - WEBSITE_URL=http://web:2000
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - TRIGGER_MENTION=UKSimRacingWebsite
    restart: unless-stopped
    networks:
      - uksimracing
    depends_on:
      - web

networks:
  uksimracing:
    driver: bridge