version: '3.8'

services:
  app:
    build: .
    container_name: uksimracing-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=2000
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - uksimracing-network
    
  nginx:
    image: nginx:alpine
    container_name: uksimracing-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - app
    networks:
      - uksimracing-network
      
  certbot:
    image: certbot/certbot
    container_name: uksimracing-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email chris@uksimracing.co.uk --agree-tos --no-eff-email --staging -d uksimracing.co.uk -d www.uksimracing.co.uk
    networks:
      - uksimracing-network

volumes:
  certbot-etc:
  certbot-var:

networks:
  uksimracing-network:
    driver: bridge