version: '3.8'

services:
  app:
    build: .
    container_name: uksimracing-app
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:80"    # HTTPS (FortiGate handles SSL termination)
      - "2000:80"   # Development/backup port
    environment:
      - NODE_ENV=production
      - PORT=80
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - uksimracing

  discord-bot:
    build: ./discord-bot
    container_name: uksimracing-discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - WEBSITE_URL=http://app:80
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - TRIGGER_MENTION=UKSimRacingWebsite
    env_file:
      - .env
    networks:
      - uksimracing
    depends_on:
      - app

networks:
  uksimracing:
    driver: bridge